;; Publishes one setting, a checkbox with the key "gym", then on every tick
;; logs its value in the settings map: "on", "off" or "unset".
(module
  (import "env" "runtime_print_message" (func $print (param i32 i32)))
  (import "env" "user_settings_add_bool"
    (func $add_bool (param i32 i32 i32 i32 i32) (result i32)))
  (import "env" "settings_map_load" (func $map_load (result i64)))
  (import "env" "settings_map_free" (func $map_free (param i64)))
  (import "env" "settings_map_get" (func $map_get (param i64 i32 i32) (result i64)))
  (import "env" "setting_value_get_bool" (func $get_bool (param i64 i32) (result i32)))
  (import "env" "setting_value_free" (func $value_free (param i64)))
  (memory (export "memory") 1)
  (data (i32.const 0) "gym")
  (data (i32.const 8) "Gym")
  (data (i32.const 16) "on")
  (data (i32.const 24) "off")
  (data (i32.const 32) "unset")
  (global $registered (mut i32) (i32.const 0))
  (func (export "update")
    (local $map i64)
    (local $value i64)
    (if (i32.eqz (global.get $registered))
      (then
        (drop (call $add_bool (i32.const 0) (i32.const 3) (i32.const 8) (i32.const 3) (i32.const 0)))
        (global.set $registered (i32.const 1))))
    (local.set $map (call $map_load))
    (local.set $value (call $map_get (local.get $map) (i32.const 0) (i32.const 3)))
    (call $map_free (local.get $map))
    (if (i64.eqz (local.get $value))
      (then (call $print (i32.const 32) (i32.const 5)) (return)))
    (drop (call $get_bool (local.get $value) (i32.const 100)))
    (call $value_free (local.get $value))
    (if (i32.load8_u (i32.const 100))
      (then (call $print (i32.const 16) (i32.const 2)))
      (else (call $print (i32.const 24) (i32.const 3))))))
